[settings]
# global random seed
seed = 231
# number of replicates per parameter set
replicates = 256
# slim script to run
script = "05-close-loci.slim"
# output directory
output_dir = "output/05-close-loci"
# number of threads to use
cores = 8
# interval to write output to disk in parameter sets
write_every = 50000
# annotate the output log files with parameter values
annotate = true
# only run first `limit' simulations (for debugging purposes)
# limit = 100
# custom slim executable path (also can be set with $SLIM_EXE environment variable)
# slim_executable = "/usr/locl/bin/slim"
custom_script = "test.scm"

[grid]
# population size during burn-in
N = 1000
# number of haplotypes seeding the experiment
nSeed = 255
# chromosome size (25Mb)
chrom = 7000000
# mutation position
mutPosA = 2000000
mutPosB = { from = 2500000, to = 5000000, num = 5 }
# starting frequency for both A and B
f0 = { from = 0.02, to = 0.1, num = 5 }
# initial r-squared 
rsq = [0.0, 0.05, 0.1, 0.5, 1.0]
# selection during expansion
selExpA = { from = 0.02, to = 0.2, num = 5 }
selExpB = 0.0
# selection during truncation
selTruncA = 0.0
selTruncB = { from = 0.02, to = 0.2, num = 5 }
# dominance coefficient
h = 0.5
# mutation rate
mu = 1.67e-9
# recombination rate
rbp = 0.0000000239
# experiment tag
tag = "far-loci"
